export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const REMOVE_ALL = 'REMOVE_ALL';

export const ADD_SELECTED_BUN = 'ADD_SELECTED_BUN';
export const REMOVE_SELECTED_BUN = 'REMOVE_SELECTED_BUN';
