export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';
export const ADD_SELECTED_INGREDIENT = 'ADD_SELECTED_INGREDIENT';
export const REMOVE_SELECTED_INGREDIENT = 'REMOVE_SELECTED_INGREDIENT';
export const ADD_DETAILED_INGREDIENT = 'ADD_SELECTED_INGREDIENT';
export const REMOVE_DETAILED_INGREDIENT = 'REMOVE_SELECTED_INGREDIENT';
